### ISSUE TITLE
Show only active farmers

### ISSUE THREAD

**Issue by BubbleTrouble14** [openchia/web#101]
I think it would look better to only show the active farmers in the farmer list. Maybe have like a filter which defualts to show only active farmers, but can also show all the farmers when turned off. And also show the active farmer count under the top stats.

**Comment by djerfy** [comment]
By default we see all farmers connected in the pool, active or inactive.
@william-gr Do you think that we can not  display farmers who have 0 point?

**Comment by william-gr** [comment]
We still need to have active farmers count in the API to show in the top stats.

**Comment by william-gr** [comment]
We should have a `farmers_active` now in stats API

**Comment by djerfy** [comment]
Done 👍
