### ISSUE TITLE
Garbled layout on Farmer Details webpage

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#11]
Steps to reproduce:

1. Open for example https://openchia.io/en/explorer/farmer/ad826a181a34b792c382ac296393db7006b3e3715317050fdfc7c933dccddcfe
2. Click "Payouts" or "Blocks"
3. Click "Partials"
4. After step 3, the webpage layout isn't the same as in step 1. Please see the screenshot.

![Screenshot_20210822_222214](https://user-images.githubusercontent.com/22368256/130369012-3980bc05-122a-4a81-a2eb-fd1b605a69e6.png)

**Comment by djerfy** [comment]
Thanks for your report. Don't have this bug on Firefox/Safari but on Google Chrome. After tests, It's caused by CSS changes (after tab change), related with **ngx-charts** module (I think). I'm going to debug this case this week.

**Comment by djerfy** [comment]
@atomsymbol a fix has been pushed, please try again

**Comment by atomsymbol** [comment]
@djerfy I confirm that the issue has been fixed. Thanks.
