### ISSUE TITLE
XCH Price in explorer dashboard

### ISSUE THREAD

**Issue by djerfy** [openchia/web#12]
Hi,

Can you add XCH Price in explorer dashboard? (api changes is required):

![image](https://user-images.githubusercontent.com/2886596/130369503-b1121189-06ef-4e67-bd44-9d034c84014f.png)

Regards

**Comment by william-gr** [comment]
Good idea, I will add backend support soon!

https://github.com/openchia/api/issues/1

**Comment by william-gr** [comment]
We should have a xch_current_price in /stats endpoint now: https://github.com/openchia/api/commit/76dbf8b69cb330cb2e447e098f1be1ad5aa7ee51
