### ISSUE TITLE
Enable Enter/Return key in farmer search field

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#144]
Current behavior: The user has to click the "Search" button after typing a search string

Desired behavior: The user can click the "Search" button or press the Enter key

A screenshot of https://openchia.io/en/explorer:

![Screenshot_20220120_183505](https://user-images.githubusercontent.com/22368256/150391898-e1398f48-1af1-4554-80fd-25f4a759e58e.png)

**Comment by djerfy** [comment]
Implementation done, it's better :) Thanks
