### ISSUE TITLE
Invalid @@Points source in en.xlf

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#172]
Previously, the translation unit "Points" had `<source>Points</source>` in [`en.xlf`](https://github.com/openchia/web/blob/main/src/locale/en.xlf). But now the source is `<source>Points (24 hours)</source>`. This caused the string "24 hodín" to be displayed twice, instead of once, on a [farmer page in locale SK](https://openchia.io/sk/explorer/farmer/bf98d9561809b923fa84acefefa9604ab5160f6821c5e8f3a58c7b79b27793e9).

![Screenshot_20220209_215144](https://user-images.githubusercontent.com/22368256/153288760-36361aa7-36a8-4542-97d2-28199df79c82.png)

````
      ....
      <trans-unit id="Points" datatype="html">
        <source>Points (24 hours)</source>
      ....
````

**Comment by william-gr** [comment]
Should be fixed, thanks!
