### ISSUE TITLE
Remove average effort in farmer page

### ISSUE THREAD

**Issue by william-gr** [openchia/web#199]
The effort we track is on the pool, not farmer level, so it makes no sense to have it there

**Comment by djerfy** [comment]
This part?

![image](https://user-images.githubusercontent.com/2886596/154547195-6638e31e-78d0-4d3d-b7b6-9aaef3833396.png)

**Comment by william-gr** [comment]
Yes, the effort in the column could probably be removed too, or renamed to Pool Effort

**Comment by djerfy** [comment]
To be deleted in the farmer page yes 👍

**Comment by djerfy** [comment]
It's done 👍
