### ISSUE TITLE
Improving pool stats graph

### ISSUE THREAD

**Issue by Johnystar98** [openchia/web#229]
adding fixed scale values
![image](https://user-images.githubusercontent.com/87005980/156162613-9f8f18b4-cf04-4d73-a01b-f4d6705156e5.png)

**Comment by djerfy** [comment]
@Johnystar98 from 8.88PiB, 13.32PiB, ... to 8PiB, 13PiB, ...?

**Comment by Johnystar98** [comment]
@djerfy yes :)

**Comment by djerfy** [comment]
Update done 👍 

![image](https://user-images.githubusercontent.com/2886596/156719528-9ded8e9d-a7de-4e63-b63a-a4e99b89cd33.png)
