### ISSUE TITLE
Lazy load farmer details

### ISSUE THREAD

**Issue by william-gr** [openchia/web#234]
Right now when the farmer details is opened it loads everything concurrently even if never used.

We should make it lazy-load each tab data, meaning only make API call requests when tab is opened.

**Comment by djerfy** [comment]
First improvement done but for a best UX, require a loading display for some cases that are long

**Comment by djerfy** [comment]
Done and available in release [v1.1.0](https://github.com/openchia/web/releases/tag/v1.1.0) 👍 
For long loading I will see if this is impacting.
