### ISSUE TITLE
Empty percentage bars in some non-English versions of the website

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#244]
The percentage-bars in the column "Utilization Space" on https://openchia.io/sk/explorer are different from https://openchia.io/en/explorer.

![Screenshot_20220311_022151](https://user-images.githubusercontent.com/22368256/157783630-24c3409c-1f7f-4609-ba98-6ef2d3228e0c.png)

**Comment by william-gr** [comment]
This is a mystery, I couldn't find the root cause yet.

**Comment by djerfy** [comment]
It's caused by separator `,` and not `.`. I look that

**Comment by william-gr** [comment]
Ah, good eye!

**Comment by djerfy** [comment]
Fixed
