### ISSUE TITLE
INVALID_AGG_SIGNATURE

### ISSUE THREAD

**Issue by kawww** [openchia/web#256]
## Behavior

farming failed

## Failure Information (for bugs)

Two nft both are good in1.2.11. If I use 1.3 or 1.3.1, one nft is good,  another nft always said errors.

farmer chia.farmer.farmer         : ERROR    Error in pooling: (7, 'The aggregate signature is invalid

If I change the pool in 1.3.1 or use 1.2.11 again, all nft are good.

**Comment by william-gr** [comment]
Hello.

Can you try to remove the pool entries in config.yaml and resync the wallet in 1.3.1?
That is supposed to clear it.

**Comment by kawww** [comment]
> Hello.
> 
> Can you try to remove the pool entries in config.yaml and resync the wallet in 1.3.1? That is supposed to clear it.

now pool login link says:

unsupported operand type(s) for /: 'int' and 'NoneType

I also deleted the config.yaml and all mainnet datas to use 1.3.1. Changed to solo/pool several times. 

only 1.2.11 both nft are good.

**Comment by william-gr** [comment]
Is that the full error? Can you post a screenshot, please?

**Comment by kawww** [comment]
> Is that the full error? Can you post a screenshot, please?

I deleted config and wallet db synced again, the error "unsupported operand type(s) for /: 'int' and 'NoneType" had gone. I can copy the pool login link now. But that nft is still invalid. 

the log says

ERROR    Error in pooling: (7, 'The aggregate signature is invalid 

![a3](https://user-images.githubusercontent.com/39939137/159147450-2a67cb8e-846a-42ef-b356-eb1de2cf6a59.jpg)

**Comment by william-gr** [comment]
I will look today if its an issue in the pool or a problem in the farmer side.

**Comment by william-gr** [comment]
Can you try again now? Made some modifications in the pool to update auth pub key.
You can try to force it by changing the payout instructions.

**Comment by kawww** [comment]
> Can you try again now? Made some modifications in the pool to update auth pub key. You can try to force it by changing the payout instructions.

Good job, two nft both are ok now, thanks very much.
![good](https://user-images.githubusercontent.com/39939137/159186647-edb7c7f8-848e-4ce0-8e68-1d720bf0320c.jpg)
.

**Comment by william-gr** [comment]
Thanks for reporting!
