### ISSUE TITLE
adding dust storm notification via spacescan api

### ISSUE THREAD

**Issue by Johnystar98** [openchia/web#259]
## Behavior

What is the behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. You get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Browser:
* Operating System:

**Comment by william-gr** [comment]
`blockchain_duststorm` and `blockchain_mempool_full_pct` added to /stats

**Comment by william-gr** [comment]
I dont really know where to put that notification

**Comment by djerfy** [comment]
With a warning popup I think, no?

**Comment by Johnystar98** [comment]
just add an icon next to a darkmode icon:)

**Comment by Johnystar98** [comment]
since popup would be probably too disturbing element, just when you wanna check some pool info
