### ISSUE TITLE
Add 🛈 to "Current Effort"

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#275]
The term "Current Effort" on page openchia.io/en/explorer/farmer/... needs an explanation.

**Comment by atomsymbol** [comment]
If a farmer didn't win any block yet and the value of "Current Effort" is `(TODAY - START_TIME) / ETW * 100%` then where does `START_TIME` come from?

**Comment by william-gr** [comment]
Creation date of NFT

**Comment by Jacek-ghub** [comment]
It would be nice, if the relevant part of that tooltip was also added to the CURRENT EFFORT on the 'explorer' page.
