### ISSUE TITLE
Refreshing any farmer page results in "500 Internal Server Error"

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#28]
Steps to reproduce:

1. Open https://openchia.io/en/explorer (Google Chrome)
2. Click any link in the column "Launcher ID"
3. Refresh the webpage (Ctrl-R or F5)

**Comment by william-gr** [comment]
Thanks! Happened after we switched to use static pages, will look shortly.

**Comment by william-gr** [comment]
Can you try now?

**Comment by atomsymbol** [comment]
The issue has been resolved. Thanks.
