### ISSUE TITLE
Farmer Details page - estimated vs. earned rewards line

### ISSUE THREAD

**Issue by Jacek-ghub** [openchia/web#297]
Could you add "Earned Rewards" line next to "Estimated Reward"?

The info is already in Rewards tab in the chart below.  Although, it would be nice to have those two lines next to each other.

I mean, I would not want to replace the info in that tab with this new line, as that tab info is providing a bit more details.  This line is just a quick overview.

**Comment by djerfy** [comment]
@william-gr Good for you with this example? (based from "Rewards" tab data)

![image](https://user-images.githubusercontent.com/2886596/173674105-f7f20e61-c202-4493-bacb-cb8a365e5298.png)

**Comment by Jacek-ghub** [comment]
last day / week / month

**Comment by djerfy** [comment]
Feature added, with icons (based from estimated rewards) :)
It's now online

**Comment by Jacek-ghub** [comment]
Works like a charm!

A quick question, on the Rewards tab, the last 24 hrs are obvious (24 h back from now).  However, what is Today?  Is that since my local time midnight, or just a duplication of the last 24 hrs (looks like a duplication - 14:10 PDT)?

**Comment by william-gr** [comment]
Today is supposed to be from 00:00 to 23:59 in UTC time. They are equal now because we are at the end of the day and no blocks were won in the 24 to end of the day interval

**Comment by Jacek-ghub** [comment]
Is there any reason on the end user facing page to use UTC instead of local time, especially if that is not pool data (general), but rather user specific data?

As you are storing each individual value in the db, wouldn't it be easier to check the current time, get the midnight, convert to UTC, and ask it for stuff newer than that?  Or conversely, ask for the last 2 days (maybe simpler / faster SQL statement), and filter out what is not applicable?

**Comment by Jacek-ghub** [comment]
By the way, as we have this new line added (super cool), maybe the code could be duplicated, and two more lines there could be added that would show the same thing for the pool?  Just asking :)

**Comment by william-gr** [comment]
Simplicity is the reason. It is all done on server-side so it would need to pass in user timezone as part of the request to make proper calculations.

Could be improved but needs proper justification to put in time for this, which costs money because time is money :laughing:

**Comment by Jacek-ghub** [comment]
If you don't mind changing the text on that tooltip, I think that:
"Icons ... are based **on** estimated rewards.  Value ... decimal **places** (**details shown** on Rewards tab)"
reads better.

**Comment by Jacek-ghub** [comment]
Also, kind of a dumb question, as I don't know Angular.  Shouldn't things like:
`xch_tb_month * (farmer.estimated_size / 1024 / 1024 / 1024 / 1024)`
be made into a back end provided function / property?  The server side code will be much faster, and looking at farmer.component.html, the maintainability of that part looks like a real headache (same thing repeated in 12 places just in that one file).  Also, readability of that code would improve.

Same goes for converting mojos to XCH, wouldn't it be easier to have two properties for those values?  Instead of:
`farmer.rewards.last_30d / 1000000000000`
to have something like
`farmer.rewards.last_30d_mojo`
`farmer.rewards.last_30d_xch   // equal to: farmer.rewards.last_30d_mojo / 1000000000000`

Those are not just cosmetic changes, but will pay in the long term, as any potential formatting changes can be done in one place, thus as you stated, paid time can be shortened.

**Comment by william-gr** [comment]
What is cheaper for us? Have the server side make the computation or the client? :P

Readability and deduplication can happen on the client side.

Thanks for the suggestions though, we will look into it

**Comment by Jacek-ghub** [comment]
> What is cheaper for us? Have the server side make the computation or the client? :P
I would turn that question around, and ask when you make more money, if your customers are happy, or when they are leaving ;)  

I really do understand that concern, as I am facing it all the time, and am also trying to balance what is done where.  In my case, I have just pure JS apps that runs basically 24/7, so following your suggestion, I should push everything to that code.  Still, the PHP on the server does quite a bit, as just one bad review by a customer that is looking for something to grab is killing ratings.  In your case, maybe I am the heaviest user of your website, and I refresh it say once per every other hour.  I assume that you have ~1,000k customers, so let's say the server gets hit once per second.  Happy customers, happy provider (more revenue).
How many customers you have?

**Comment by william-gr** [comment]
This is not a business model for us. Chia is not profitable, we as a pool are not profitable, we have been losing money for a whole year to keep it running. I am doing it because I like it, thats the only reason.

You have to pick your battles when you're in this position. Where should you spend your time? Rewriting a piece of code that is already there that you make things load 0.1s faster? Or adding new functionality and squashing bugs?

I don't follow your comment about taxes, we already provide that.

As far as discounts, thats just incentive, there is no simple way to quantify how helpful that is or not.
Turning off a farm will not reset your discount. Only happens if you actually leave the pool.

**Comment by Jacek-ghub** [comment]
> Chia is not profitable

I hear you.  Every day when I wake up, I ask myself whether to continue.  As you mentioned already, they don't do enough to make the ecosystem more friendly, easier to use.  It looks like they put 100% of their efforts to support that IPO, and that also went down the drain with the current market.

> I don't follow your comment about taxes, we already provide that.

Oh, that was just to be more active on that forum, and let people know that you are out there.

**Comment by Jacek-ghub** [comment]
@djerfy  Hey, love those latest code changes!! :)

Seeing how you added that _usd prop, it implies that if at any point you want to localize currency, you already have 90% of the code done!! 

Just that one simple line shows the power of what can be done, and what effect it has on potential future changes.
