### ISSUE TITLE
Stats page - add "luck" chart

### ISSUE THREAD

**Issue by Jacek-ghub** [openchia/web#300]
I was looking at POOL BLOCKS chart the Stats page, but I have to say that I am a bit confused.  To me, that chart doesn't have much value.  Sure, nice green blocks that show how the pool performs, but without any reference what those really mean (other than one day had more wins than the other).

What I would rather want to see is a chart with those "1 DAY", ... buttons underneath, but rather being a line chart showing pool's luck for a given period and normalized to 100%.  Actually, also giving the average for a given period.  Kind of a chart for Pool Effort table from the Explorer page.

Even starting with the "Effort" value added to the current POO BLOCKS chart would be a nice addition (on the hover effect that currently shows date / # of blocks).

**Comment by Jacek-ghub** [comment]
Not sure if we are talking about the same thing.  I am not asking about charting what pool is supposed to win, but rather what pool has already won.

Take a look at Space pool / Pool Luck chart - https://pool.space/statistics.  That is just percentage value of what happened before.

**Comment by william-gr** [comment]
Its essentially the same thing

**Comment by Jacek-ghub** [comment]
That's correct.  However, in case of Space pool chart, the end user doesn't need to calculate whether the pool operates at 80% or 120%, as the chart is normalized for 100% responses.  In case of Open pool, not seeing the luck, we can also assume that those highest blocks are behind with the luck (or vice versa) - there is no reference point on those charts.

**Comment by djerfy** [comment]
@Jacek-ghub

Implementation is done and available in [stats page](https://openchia.io/en/stats). It's luck chart for each block won.
Next step is an average (luck) per day.
