### ISSUE TITLE
Add referral system

### ISSUE THREAD

**Issue by william-gr** [openchia/web#51]
Idea is farmers can refer the pool to others and get a percentage of the pool fee from the referred farmers.

This would be validated upon login of the referred farmer, confirming the launcher id of the referrer.

**Comment by atomsymbol** [comment]
The max _theoretical_ pool fee is 1.75 XCH per block found. If the pool fee is 1%, this makes 1.75/100 = 0.0175 XCH. If the total allocation to the referral system is, say, 10% of the pool fee, this makes 0.0175/10 = 0.00175 XCH = 0.3€ which would be divided among the farmers participating in the referral system (per block found). If the pool finds 10 blocks per month: 0.0175 XCH/month = 3 €/month.

**Comment by william-gr** [comment]
Your math should be over estimated XCH/TiB per day for the people someone referes to the pool.

Agree its not much but its an incentive. Better than nothing.

**Comment by atomsymbol** [comment]
> Your math should be over estimated XCH/TiB per day for the people someone refers to the pool.

Yes, I know. I didn't want to overcomplicate my post.

**Comment by william-gr** [comment]
This has been implemented.
