### ISSUE TITLE
Web browser tab always consumes 5-10% of CPU time

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#60]
Steps to reproduce this issue:

1. Open, for example, https://openchia.io/en/explorer in Google Chrome
2. Press Shift+Esc to open Google Chrome's task manager

Expected results:

- OpenChia browser tab consumes 1-2% of CPU time when viewing [the explorer](https://openchia.io/en/explorer)
- OpenChia browser tab consumes 0% of CPU time when viewing [a farmer](https://openchia.io/en/explorer/farmer/bf98d9561809b923fa84acefefa9604ab5160f6821c5e8f3a58c7b79b27793e9)

Actual results: The browser tab consumes 5-10% of CPU time, in either of the above two cases.

![Screenshot_20211016_042357](https://user-images.githubusercontent.com/22368256/137570306-f05d4d0e-85e5-4d1a-9508-c42bb737aa00.png)

**Comment by william-gr** [comment]
Finally figured it out, its the animations in the top, the circles that move :)

**Comment by atomsymbol** [comment]
I wasn't aware that they were moving :)

Enabling "Paint flashing" and "Layer borders" in Google Chrome inspector shows that in addition to the visible moving circles there are two invisible ones:

![Screenshot_20220211_072647](https://user-images.githubusercontent.com/22368256/153546687-52ffb46c-b5f4-4ebc-b2d6-b1ed00300757.png)
