### ISSUE TITLE
For consideration: Claim pool addresses on XCHSCAN

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#63]
The two Pool Wallets displayed on https://openchia.io/en/explorer are referring xchscan.com, but the "Address information" fields there are empty. Claiming an address requires a deposit of 0.001 XCH from the address, though. https://xchscan.com/claim-xch-address

**Comment by william-gr** [comment]
I make the claim for the first address. I will wait it get confirmed to do the second.

**Comment by atomsymbol** [comment]
I thought that the deposit of 0.001 XCH would be returned back in a few minutes after claiming the address took effect (because xchscan says that it is a deposit, not a payment). This doesn't seem to be the case (or it takes much longer than a few minutes).

**Comment by william-gr** [comment]
It doesn't come back. 0.001 XCH is their price for changing it.

![image](https://user-images.githubusercontent.com/56250/140494879-aa92e571-2adc-4024-8cf9-16436958525b.png)

**Comment by william-gr** [comment]
Done
