### ISSUE TITLE
Possibly invalid syntax in translation sources

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#64]
Hello. https://localazy.com/p/openchia/ contains strings such as `<ph disp="ber { return th" equiv="INTERPOLATION" id="0" />`. The `"ber { return th"` doesn't look like a correct expression in any programming language. Is the `"ber { return th"` there intentionally, or by mistake?

**Comment by atomsymbol** [comment]
> We re trying to move away from localazy as it has a limit of strings and we have surpassed that.

Hello. Are there some news in relation to moving away from localazy? Schedule?

**Comment by william-gr** [comment]
Hello, unfortunately not yet. We are having a hard time finding a replacement. All of them seem to impose a low limit and their pricing make it a show stopper for us at the moment as we are currently operating on loss with the pool.

**Comment by atomsymbol** [comment]
Just a question about the infrastructure on which openchia.io is running: Is openchia.io paying for the amount of data transferred over the network IN/OUT per month, or do network data transfers have a fixed monthly cost irrespective of the amount of data?

**Comment by atomsymbol** [comment]
> ... we are currently operating on loss with the pool.

Just a thought: According to https://xchscan.com/charts/netspace, Chia netspace growth stopped at the start of September. It is possible that Chia's netspace will decrease by a few petabytes as a result of more farmers reallocating their HDD's to Chives (Chives plots are currently incompatible with Chia plots), which in turn should improve XCH-per-TiB revenue by a few percent.

**Comment by atomsymbol** [comment]
> ... Chia's netspace will decrease by a few petabytes ...

Typo: petabytes -> exabytes.

**Comment by william-gr** [comment]
> Just a question about the infrastructure on which openchia.io is running: Is openchia.io paying depending on the amount of data transferred over the network IN/OUT per month, or do network data transfers have a fixed monthly cost irrespective of the amount of data transferred?

We have a fixed amount for data transfer which should be more than enough for the foreseeable future.

**Comment by atomsymbol** [comment]
> Hello, unfortunately not yet. We are having a hard time finding a replacement. All of them seem to impose a low limit and their pricing make it a show stopper for us at the moment as we are currently operating on loss with the pool.

Is the pricing of localazy still a show stopper?

Is the pool still operating at a loss?

**Comment by william-gr** [comment]
Yes, that is still the case unfortunately, I am investigating alternatives

**Comment by william-gr** [comment]
https://translation.openchia.io/

It will be the source of truth now, handling these sources will be easier too.

**Comment by atomsymbol** [comment]
> https://translation.openchia.io/
> 
> It will be the source of truth now, handling these sources will be easier too.

Cool. Thanks.
