### ISSUE TITLE
Farmer details page is getting slower

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#68]
Pages starting with https://openchia.io/en/explorer/farmer/ are much slower than they used to be.

- It now takes about 8 seconds for the partials chart to be rendered with a cold server's cache,
- and about 5 seconds with a warm server's cache (`Ctrl-R` in the web browser)

Web browser CPU usage (on the machine which is running the web browser) is close to zero, which means that this might be an OpenChia server issue, or a timer issue, or an issue of how data is being sent over the network from the server to the browser.

**Comment by william-gr** [comment]
Can you verify if its better now?

**Comment by atomsymbol** [comment]
Yes, it is much faster now. Thanks.

@william-gr I see 12 `INVALID_SIGNAGE_OR_EOS` in farmer details from 2:30:40 AM to 2:40:50 AM. Are these failures related to the process of fixing this issue? They started to happen exactly when you posted your message to github that the issue is fixed.

**Comment by william-gr** [comment]
Sort of, I took the opportunity to update the node too so it got momentarily out of sync.
