### ISSUE TITLE
30-day effort average isn't taking the current effort into account

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#70]
Today, the box "EFFORT" on the web page is based on the following computation (10 blocks found in the past 30 days):

    (33+143+44+134+250+15+58+98+25+108) / 10 = 90%

However, the box "CURRENT EFFORT" contains the number 359%. If this was taken into account, the computation would be:

    (359 + 33+143+44+134+250+15+58+98+25+108) / 11 = 115%

----

![Screenshot_20211121_173031](https://user-images.githubusercontent.com/22368256/142770558-d2c3c8d8-f74b-4026-871d-62b779edd65e.png)

**Comment by atomsymbol** [comment]
A better formula that works if "CURRENT EFFORT" is close to zero:

    (abs(359-100) + 33+143+44+134+250+15+58+98+25+108) / 11 = 106%

    (abs(0-100) + 33+143+44+134+250+15+58+98+25+108) / 11 = 92%

**Comment by atomsymbol** [comment]
Fix of the previous formula for CURRENT EFFORT close to 100%:

    (max(359,100) + 33+143+44+134+250+15+58+98+25+108) / 11 = 115%

    (max(100,100) + 33+143+44+134+250+15+58+98+25+108) / 11 = 92%

    (max(0,100) + 33+143+44+134+250+15+58+98+25+108) / 11 = 92%

**Comment by william-gr** [comment]
Good catch, I will try to implement it this week after some pool changes we need to make.

**Comment by atomsymbol** [comment]
[2021-12-03 16:25 CET] The EFFORT displayed on the web page is 92%, while yesterday it was 106% if I remember correctly. CURRENT EFFORT is 332%.

**Comment by william-gr** [comment]
Yeah, a block gets out of the 30-day range and changes the average... Adding this fix would make it smoother

**Comment by atomsymbol** [comment]
I am closing this issue because with 60 blocks per month it is no longer an issue.
