### ISSUE TITLE
Sorting of farmers after a block is found

### ISSUE THREAD

**Issue by atomsymbol** [openchia/web#95]
The order in which farmers are being displayed, immediately after a block is found, is random. If pool space becomes larger in the future then the random sorting of farmers will be occurring with a higher frequency compared to today. It would be nice to sort farmers according to Points, and **then (if Points are equal) by Difficulty or by Estimated_Space**.

Note: On some other pools, PPLNS means something slightly different than PPLNS on OpenChia because the points on the other pools aren't being reset to zero after a block is found. For example: https://www.chivespool.com/en/farmer/21d049c422f17a3a0b5f0d270dd9e8129162098984dd762699bdd737eaf64698

![Screenshot_20211221_220909](https://user-images.githubusercontent.com/22368256/146998333-bb7d0fb7-639e-488d-ba44-85aad7d53d2f.png)

**Comment by william-gr** [comment]
We will be changing to PPLNS of 24hrs shortly which will make this a non issue

**Comment by william-gr** [comment]
PPLNS has been implemented
